---
- name: Read secret from agnostics_secrets_namespace
  k8s_info:
    namespace: "{{ agnostics_secrets_namespace }}"
    name: "{{ agnostics_placement_cloud }}"
    api: v1
    kind: Secret
  register: r_secret

- name: Try suffix '-no-repos' -- Read secret from agnostics_secrets_namespace
  k8s_info:
    namespace: "{{ agnostics_secrets_namespace }}"
    name: "{{ agnostics_placement_cloud }}-no-repos"
    api: v1
    kind: Secret
  register: r_secret
  when: r_secret.resources | length == 0

- name: Fail if no secret found
  when: r_secret.resources | length == 0
  fail:
    msg: >-
      No secret {{ agnostics_placement_cloud }} found in namespace
      {{ agnostics_secrets_namespace }}

- name: Convert secret data (decode base64)
  read_secret:
    secret: "{{ r_secret.resources[0] }}"
  register: r_secret_converted

- name: Inject secrets into dynamic_job_vars
  set_fact:
    dynamic_job_vars: >-
      {{ vars.dynamic_job_vars
      | default({})
      | combine(r_secret_converted.data, recursive=True) }}
