---
- name: Read secret from agnostics_secrets_namespace
  k8s_info:
    namespace: "{{ agnostics_secrets_namespace }}"
    name: "{{ agnostics_placement_cloud }}"
    api: v1
    kind: Secret
  register: r_secret

- name: Try suffix '-no-repos' -- Read secret from agnostics_secrets_namespace
  k8s_info:
    namespace: "{{ agnostics_secrets_namespace }}"
    name: "{{ agnostics_placement_cloud }}-no-repos"
    api: v1
    kind: Secret
  register: r_secret_no_repo
  when: r_secret.resources | length == 0

- name: Fail if no secret found
  when: >-
    r_secret.resources | length == 0
    and
    r_secret_no_repo.resources | length == 0
  fail:
    msg: >-
      No secret {{ agnostics_placement_cloud }} found in namespace
      {{ agnostics_secrets_namespace }}

- name: Use defined secret
  set_fact:
    n_secret: "{% if r_secret.resources|length == 0 %}{{ r_secret_no_repo }}{% else %}{{ r_secret }}{% endif %}"

- name: Convert values from base64 and Inject secrets into dynamic_job_vars
  set_fact:
    dynamic_job_vars: >-
      {{ vars.dynamic_job_vars
      | default({})
      | combine(n_secret.resources[0].data | convert_secret, recursive=True) }}
