---
- name: Remove a placement
  uri:
    url: "{{ agnostics_url }}/api/v1/placements/{{ uuid }}"
    validate_certs: "{{ agnostics_validate_certs }}"
    return_content: true
    method: DELETE
    status_code: [200, 404]
    url_username: "{{ agnostics_username }}"
    url_password: "{{ agnostics_password }}"
  register: r_placement
  retries: "{{ agnostics_retries }}"
  delay: "{{ agnostics_delay }}"
  until: r_placement is succeeded

- name: Debug info
  debug:
    msg: "placement {{ uuid }}: {{ r_placement.json.message }}"
